USE [master]
GO

/****** Object:  Database [LDLogistics]    Script Date: 2021/11/07 11:50:33 ******/
DROP DATABASE [LDLogistics]
GO

/****** Object:  Database [LDLogistics]    Script Date: 2021/11/07 11:50:34 ******/
CREATE DATABASE [LDLogistics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LDLogistics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LDLogistics.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LDLogistics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LDLogistics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LDLogistics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LDLogistics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LDLogistics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LDLogistics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LDLogistics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LDLogistics] SET ARITHABORT OFF 
GO

ALTER DATABASE [LDLogistics] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LDLogistics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LDLogistics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LDLogistics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LDLogistics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LDLogistics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LDLogistics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LDLogistics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LDLogistics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LDLogistics] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LDLogistics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LDLogistics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LDLogistics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LDLogistics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LDLogistics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LDLogistics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LDLogistics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LDLogistics] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LDLogistics] SET  MULTI_USER 
GO

ALTER DATABASE [LDLogistics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LDLogistics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LDLogistics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LDLogistics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LDLogistics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LDLogistics] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LDLogistics] SET  READ_WRITE 
GO

